sudo: false

language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

branches:
  except:
  - gh-pages
